Repository harshit1142/e-commerce, pull requests merged in 2024-10, with the labels that each got.

#6 Update contributorsList.js
  contributors/contributorsList.js
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#7 Contributors readme file
  README.md
Labels: hacktoberfest-accepted

#8 added products
  contributors/contributorsList.js
  package-lock.json
  src/App.js
Labels: hacktoberfest-accepted

#11 Add a Product
  src/App.js
Labels: hacktoberfest-accepted

#20 Create doc.md
  doc.md
Labels: hacktoberfest-accepted

#10 Add a product
  package-lock.json
  src/App.js
Labels: hacktoberfest-accepted

#22 Added react-icons dependency
  package.json
Labels: hacktoberfest-accepted

#28 changes in card ui
  src/Components/Card.js
Labels: hacktoberfest-accepted

#29 UI/UX changes made
  .all-contributorsrc
  contributors/contributorsList.js
  src/App.css
  src/Components/Card.js
Labels: hacktoberfest-accepted

#33 #1 Add a product
  src/data/products.json
Labels: good first issue, hacktoberfest-accepted

#34 Fix the issue of toggle and used material ui for the card for better ui
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/Components/Card.js
  src/Components/CardCom.js
Labels: hacktoberfest-accepted

#43 Added Search functionality
  src/App.js
  src/Components/Navbar.js
Labels: hacktoberfest-accepted

#44 Added Product issue #1
  src/data/products.json
Labels: hacktoberfest-accepted

#46 Added About us page - issue #41
  src/App.js
  src/Components/AboutUs.css
  src/Components/AboutUs.js
  src/Components/Main.js
  src/Components/Navbar.js
Labels: hacktoberfest-accepted

#47 Added a Signup page
  src/App.js
  src/Components/Navbar.js
  src/Components/signup.css
  src/Components/signup.js
Labels: hacktoberfest-accepted

#48 #19Product_added
  src/data/products.json
Labels: hacktoberfest-accepted

#50 Card Styling improvement
  contributors/contributorsList.js
  src/App.css
  src/App.js
  src/Components/CardCom.js
Labels: hacktoberfest-accepted

#51 Added apple product #1
  src/data/products.json
Labels: hacktoberfest-accepted

#52 Added samsung products
  src/data/products.json
Labels: hacktoberfest-accepted

#55 Added Contact Us Page issue#53
  package-lock.json
  package.json
  src/App.js
  src/Components/AboutUs.css
  src/Components/AboutUs.js
  src/Components/ContactUs.js
  src/Components/Navbar.js
  src/Components/Style.css
Labels: hacktoberfest-accepted

#56 Add sorting component
  src/Components/Main.js
Labels: hacktoberfest-accepted

#58 Added: Products in src/products.json
  src/data/products.json
Labels: hacktoberfest-accepted

#61 LavaAgni 3 5G Added Add a product [Open to ALL] #1
  src/data/products.json
Labels: hacktoberfest-accepted

#63 Fixed Description Length for Product Listing Cards and align buttons (#62)
  src/Components/CardCom.js
Labels: hacktoberfest-accepted

#64 added wishlist feature
  src/App.css
  src/App.js
  src/Components/CardCom.js
  src/Components/Main.js
  src/Components/WishList.js
Labels: hacktoberfest-accepted

#67 Add more products
  src/data/products.json
Labels: hacktoberfest-accepted

#70 BUG: Edit the Re-Enter Password Field
  src/Components/signup.js
Labels: hacktoberfest-accepted, gossc-ext

#73 BUG: Signup btn Not Working
  package.json
  src/Components/signup.js
  src/index.js
Labels: hacktoberfest-accepted

#75 Update products.json
  src/data/products.json
Labels: hacktoberfest-accepted

#68 added AddToCart Page
  src/App.js
  src/Components/CardCom.js
  src/Components/CartPage.js
  src/Components/Main.js
  src/Components/Navbar.js
  src/Components/Style.css
Labels: hacktoberfest-accepted

#78 adding new products in website
  src/data/products.json
Labels: hacktoberfest-accepted

#79 BUG: Signup form Validation
  src/Components/signup.js
Labels: hacktoberfest-accepted, gossc-ext

#87 BUG: Edit the Allignment of Cart
  src/Components/CartPage.js
Labels: hacktoberfest-accepted

#91 BUG: Edit path for not exist
  src/App.js
  src/Components/Error.jsx
Labels: hacktoberfest-accepted, gossc-ext

#90 changes in wishlist.js and homepage ui
  src/Components/CardCom.js
  src/Components/Main.js
  src/Components/Style.css
  src/Components/WishList.js
Labels: hacktoberfest-accepted

#93 fixes:error while running locally
  src/Components/CardCom.js
  src/Components/Main.js
  src/Components/signup.js
Labels: hacktoberfest-accepted

#96 Added a product
  src/data/products.json
Labels: hacktoberfest-accepted

#107 Resolve-parsing-error
  package-lock.json
  src/Components/Main.js
Labels: hacktoberfest-accepted
